version: '3.8'

services:
  chat-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./content:/app/content
      - ./logs:/app/logs
    environment:
      - DEBUG=1
      - ENVIRONMENT=development
    env_file:
      - .env
    restart: unless-stopped 